export const stockData = [
    {
      id: 1,
      name: "Samsung Galaxy S22",
      price: 5899,
      image: "https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2022/2/pr_2022_2_4_14_26_35_40_00.jpg",
      descryption: "Oto Samsung Galaxy S22 Ultra, który na nowo definiuje szybkość i płynność działania. Profesjonalny aparat został stworzony do nocnych zdjęć i wideo. Bateria o dużej pojemności i ultraszybkie ładowanie pozwolą Ci dłużej korzystać ze smartfona. Duży ekran to jeszcze więcej możliwości. Oglądaj ulubione filmy i poczuj się jak w kinie.",
    },
    {
        id: 2,
        name: "Xiaomi POCO X3 PRO",
        price: 1199,
        image: "https://www.techinn.com/f/13810/138107446/xiaomi-poco-x3-pro-6gb-128gb-6.67-smartfon.jpg",
        descryption: "Genialna sylwetka oraz ogromny ekran to nowy Xiaomi POCO X3 PRO 8/256 GB czarny. Otwórz się na nowe doznania w swojej ulubionej grze i nigdy nie zwalniaj, a efekt smużenia nigdy nie zagości. Matryca ma odświeżanie 120 Hz oraz wielkość 6,67 cala dzięki temu każda akcja będzie płynna.",
    },
    {
        id: 3,
        name: "Apple iPhone 11",
        price: 2599,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone11-green-select-2019_GEO_EMEA?wid=834&hei=1000&fmt=jpeg&qlt=95&.v=1567021766404",
        descryption: "Nowy system dwóch aparatów pozwala uchwycić więcej. Najszybszy czip w historii smartfonów i bateria na cały dzień – jeszcze więcej zdziałać. A dzięki wideo o jakości nieosiągalnej dla żadnego innego smartfona zapisane wspomnienia będą wyglądać piękniej niż kiedykolwiek.",
    },
    {
        id: 4,
        name: "Samsung Galaxy M12",
        price: 699,
        image: "https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2021/5/pr_2021_5_4_12_29_2_512_00.jpg",
        descryption: "Samsung Galaxy M12 64GB czarny to połączenie nowoczesnego wyglądu i technologii. Rób zdjęcia, wykorzystując do tego system czterech aparatów. Wybierz obiektyw, w zależności od aktualnych potrzeb.",
    },
    {
        id: 5,
        name: "Apple iPhone 13",
        price: 4099,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-pink-select-2021?wid=470&hei=556&fmt=jpeg&qlt=95&.v=1629842709000",
        descryption: "Apple iPhone 13 128 GB Pink to smartfon, z którym każda praca i rozrywka będzie niezwykle przyjemna. Wydajny procesor wraz z pojemną baterią zadbają, aby w niczym Cię nie ograniczać. Aparat został ulepszony, wiec teraz Twoje zdjęcia i filmy będą jeszcze ciekawsze, a ich jakość doskonała. ",
    },
    {
        id: 6,
        name: "OnePlus 8 Pro",
        price: 2899,
        image: "https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2020/4/pr_2020_4_10_7_23_10_275_10.jpg",
        descryption: "Obejrzyj poniższy materiał wideo i dowiedz się, jakie zalety posiada smartfon OnePlus 8 Pro z 12 GB pamięci RAM oraz 256 GB wbudowanej pamięci wewnętrznej. W jedyne 60 sekund zapoznaj się z produktem i odkryj jego najważniejsze cechy.",
    },
    {
        id: 7,
        name: "Xiaomi Redmi Note 10S",
        price: 1249,
        image: "https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/29/2988262/Smartfon-XIAOMI-Redmi-Note-10s-6-64GB-6.43-Szary-33431-front-tyl-napis.jpg",
        descryption: "Bądź już stale na bieżąco z poszukiwaczem przygód. Oto Xiaomi Redmi Note 10S 64 GB szary. Jego obudowa i linie konstrukcji zawrócą Ci w głowie. Idealnie wkomponowany aparat ma w sobie cztery obiektywy. Dzięki nim uchwycisz już każdą chwilę lub przedmiot. ",
    },
    {
        id: 8,
        name: "Nokia 6310",
        price: 239,
        image: "https://f00.esfr.pl/foto/1/91628828561/48738bd908ba804167d2b5db58030619/nokia-tel-kom-nokia-6310-ta-1400-ds-pl-black,91628828561_8.jpg",
        descryption: "Nowa Nokia 6310 przyjmuje kultową sylwetkę oryginału i aktualizuje ją dzięki nowym, wspaniałym dodatkom, takim jak duży zakrzywiony ekran, poprawiona czytelność, a także szereg klasycznych funkcji, które znasz i lubisz: bezprzewodowe radio FM, imponująca bateria, która może wytrzymać tygodnie między ładowaniami i  klasyczna gra Snake.",
    },
  ];